FROM node:22

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ARG INDEXER_API
ARG INDEXER_WS
# not needed for production
ARG ANVIL_MARKETPLACE 
ARG MODE

ENV NEXT_PUBLIC_INDEXER_API=$INDEXER_API
ENV NEXT_PUBLIC_INDEXER_WS=$INDEXER_WS
ENV NEXT_PUBLIC_ANVIL_MARKETPLACE=$ANVIL_MARKETPLACE
ENV NEXT_PUBLIC_MODE=$MODE

RUN npm run build

CMD ["npm", "start"]
