FROM node:22

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ARG INDEXER_API
ARG INDEXER_WS
ARG MODE

ENV NEXT_PUBLIC_INDEXER_API=$NEXT_PUBLIC_INDEXER_API
ENV NEXT_PUBLIC_INDEXER_WS=$NEXT_PUBLIC_INDEXER_WS
ENV NEXT_PUBLIC_MODE=$MODE

RUN npm run build

CMD ["npm", "start"]
