FROM node:22

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ARG NEXT_PUBLIC_INDEXER_API
ARG NEXT_PUBLIC_INDEXER_WS
ARG NEXT_PUBLIC_ANVIL_RPC_URL
ARG NEXT_PUBLIC_MARKETPLACE_ADDR

ENV NEXT_PUBLIC_INDEXER_API=$NEXT_PUBLIC_INDEXER_API
ENV NEXT_PUBLIC_INDEXER_WS=$NEXT_PUBLIC_INDEXER_WS
ENV NEXT_PUBLIC_ANVIL_RPC_URL=$NEXT_PUBLIC_ANVIL_RPC_URL
ENV NEXT_PUBLIC_MARKETPLACE_ADDR=$NEXT_PUBLIC_MARKETPLACE_ADDR

RUN npm run build

CMD ["npm", "start"]
