import type { Metadata } from 'next'

import './globals.css'

import AppShell from './AppShell'
import { Providers } from './providers/Providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" data-theme="cyber-void" suppressHydrationWarning>
      <body suppressHydrationWarning>
        {/* <a
          href="#forward-main"
          className="sr-only focus:not-sr-only focus:underline absolute top-2 left-2 z-50"
        >
          Skip Header
        </a> */}
        <Providers>
          <AppShell>{children}</AppShell>
        </Providers>
      </body>
    </html>
  )
}
